### ISSUE TITLE
Dynamic size of buttons in PlayBar control bar on panel

### ISSUE THREAD

**Issue by MurzNN** [jsmitar/PlayBar#1]
I use KDE Plasma panel with large height, but PlayBar widget have fixed small size of bars, this is not comfortable to use, here is screenshot:
http://wstaw.org/m/2014/07/23/plasma-desktopMJ6726.png
Can you create dynamic-sized buttons or change button size in settings?

**Comment by jsmitar** [comment]
I see, I think adding dynamic size, it is more convenient.

**Comment by MurzNN** [comment]
Thanks for quick fixing, but where can I get updated version?

**Comment by jsmitar** [comment]
You find it in the branch of "shortcuts".
Go to the configuration window. 
https://mega.co.nz/#!49M3kSKY!Nx1OjvQwaYsveEPzbF2dPpjgdeB6qjatKVLyrxF4-lw

Notify me if you think it can be improved. Thank you

**Comment by MurzNN** [comment]
Thanks, I download it succesfully from this link, but didn't see updates here https://github.com/audoban/PlayBar/commits/master  - this is strange :)
Selecting size manually works well, this is enough for me.

If you have time, will be good to add checkbox "Full height" in bar size that auto-resize them to full height of widget. And maybe "padding" option for tune up free space size from corners.

**Comment by jsmitar** [comment]
https://github.com/audoban/PlayBar/tree/shortcuts it's here. :+1: 
I'll try to improve this feature in the next version. 
Que tenga buen día. xP
