### ISSUE TITLE
Add support for Plasma Desktop Shell Play, Pause, Toggle, Next, Previous global keyboard shortcuts

### ISSUE THREAD

**Issue by MurzNN** [jsmitar/PlayBar#2]
Before PlayBar I use Play Control plasmoid http://kde-apps.org/content/show.php?content=144437
It is too slow on initializing and have some other problems (encoding, button size), so your plasmoid is much better!

Play Control plasmoid acts on KDE Global Keyboard shortcuts (Plasma Desktop Shell Play, Pause, Toggle, Next, Previous) out-of-the-box (I only add it to panel and hotkeys works).

But when I replace Play Control to PlayBar, shortcuts stops working, if I place it back - works again.

Can you add support for Plasma Desktop Shell Play, Pause, Toggle, Next, Previous global keyboard shortcuts?

**Comment by jsmitar** [comment]
Sure. Currently I am developing.
But I have not had much free time, but I do what I can.

Have a nice day.

**Comment by jsmitar** [comment]
Added Global Shortcuts :D

**Comment by MurzNN** [comment]
Thanks! But seems that after integrating this feature - plasmoid becomes unavailable in quick install via Plasma interface (Download new plasma widgets), we need to compile it manually, because it contains C++ code :(
I try to compile it on my Kubuntu 14.04 system, but can't do it, I will open separate bug report.

If this feature cannot be done without converting plasmoid to binary, maybe will be better to create two versions - lite and full? Because binary plasmoids are too hard for installing :(
