### ISSUE TITLE
Can't compile PlayBar 0.6.1 with cmake on Ubuntu (Kubuntu) 14.04

### ISSUE THREAD

**Issue by MurzNN** [jsmitar/PlayBar#3]
Because new version of widget converts from script to binary, we must compile it instead of installing via Plasma interface. 

But I can't compile (make) it on my  Ubuntu (Kubuntu) 14.04 AMD64 system. 
`cmake` command works well with QT_QT_INCLUDE_DIR option (without this option - it isn't found qt libraries), but on `make` I got the error, here is output:

> cmake -DCMAKE_INSTALL_PREFIX=/usr .. -DQT_QT_INCLUDE_DIR=/usr/include/qt4; make
> ....
> [ 66%] Building CXX object engine/CMakeFiles/plasma_engine_playbar.dir/service.o
> In file included from /home/murz/temp/2014-08/PlayBar-0.6.1/engine/service.cpp:46:0:
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:15:2: error: #error "This file was generated using the moc from 5.2.1. It"
>  #error "This file was generated using the moc from 5.2.1. It"
>   ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:16:2: error: #error "cannot be used with the include files from this version of Qt."
>  #error "cannot be used with the include files from this version of Qt."
>   ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:17:2: error: #error "(The moc has changed too much.)"
>  #error "(The moc has changed too much.)"
>   ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:22:5: error: ‘QByteArrayData’ does not name a type
>      QByteArrayData data[1];
>      ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:28:24: error: ‘QByteArrayData’ was not declared in this scope
>          - idx \* sizeof(QByteArrayData) \
>                         ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:32:1: note: in expansion of macro ‘QT_MOC_LITERAL’
>  QT_MOC_LITERAL(0, 0, 14)
>  ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:29:5: error: ‘Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET’ was not declared in this scope
>      )
>      ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:32:1: note: in expansion of macro ‘QT_MOC_LITERAL’
>  QT_MOC_LITERAL(0, 0, 14)
>  ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:63:69: error: ‘const struct qt_meta_stringdata_PlayBarService_t’ has no member named ‘data’
>      { &Service::staticMetaObject, qt_meta_stringdata_PlayBarService.data,
>                                                                      ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc: In member function ‘virtual const QMetaObject\* PlayBarService::metaObject() const’:
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:70:57: error: ‘class QObjectData’ has no member named ‘dynamicMetaObject’
>      return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
>                                                          ^
> /home/murz/temp/2014-08/PlayBar-0.6.1/build/engine/service.moc:71:1: error: control reaches end of non-void function [-Werror=return-type]
>  }
>  ^
> cc1plus: some warnings being treated as errors
> make[2]: **\* [engine/CMakeFiles/plasma_engine_playbar.dir/service.o] Error 1
> make[1]: **\* [engine/CMakeFiles/plasma_engine_playbar.dir/all] Error 2
> make: **\* [all] Error 2

Can you help me with compiling options?

**Comment by jsmitar** [comment]
Tell me please, if you installed kdebase-workspace-dev?

**Comment by jsmitar** [comment]
The reason I converted to binary PlayBar is because JS/QML did not offer me the ability to create the Global Shortcuts. :(

**Comment by MurzNN** [comment]
Yes, I have install kdebase-workspace-dev, kde-workspace-dev, libqt4-dev and some other libs by dependencies.

**Comment by MurzNN** [comment]
> The reason I converted to binary PlayBar is because JS/QML did not offer me the ability to create the Global Shortcuts. :(

But Play Control Plasmoid Script (http://opendesktop.org/content/show.php?content=144437) support Global Shortcuts and works well without compiling, maybe you can look on it code?

**Comment by MurzNN** [comment]
Oh, seems that Play Control Plasmoid Script written in Python, not in JS/QML, but installing plasmoids without compiling are much more comfortable way for most of users. 
Here is strings from main.py file of Play Control Plasmoid Script:

> ```
>             prev_action.setGlobalShortcut(KShortcut(Qt.Key_MediaPrevious))
>             backward_action.setGlobalShortcut(KShortcut(Qt.SHIFT | Qt.Key_MediaPrevious))
>             play_pause_action.setGlobalShortcut(KShortcut(Qt.Key_MediaTogglePlayPause))
>             play_action.setGlobalShortcut(KShortcut(Qt.Key_MediaPlay))
>             pause_action.setGlobalShortcut(KShortcut(Qt.Key_MediaPause))
>             stop_action.setGlobalShortcut(KShortcut(Qt.Key_MediaStop))
>             forward_action.setGlobalShortcut(KShortcut(Qt.SHIFT | Qt.Key_MediaNext))
>             next_action.setGlobalShortcut(KShortcut(Qt.Key_MediaNext))
>             quit_action.setGlobalShortcut(KShortcut())
> ```

**Comment by jsmitar** [comment]
Exactly, but I did not want to add more load to the cpu. Now that would be needed to run KDE Python binding.

**Comment by jsmitar** [comment]
Seems to be a problem with the automoc tool, let me do a test on Kubuntu and I'll tell you.

**Comment by jsmitar** [comment]
I tried it on Kubuntu 14.04 and I had no problem building the package. I just installed the KDE SDK package. See it http://packages.ubuntu.com/trusty/kde-developer-sdk

http://www.hostingpics.net/viewer.php?id=326215screenshot13.png
Download KDE SDK and try once again.

**Comment by jsmitar** [comment]
I'll close this thread
